-- DO
-- $$
--     BEGIN
--         BEGIN
--             CREATE TYPE public.genre_type AS ENUM (
--                 'ДРАМА',
--                 'КОМЕДИЯ',
--                 'ТРАГЕДИЯ',
--                 'МЮЗИКЛ',
--                 'ОПЕРА',
--                 'БАЛЕТ',
--                 'МЕЛОДРАМА',
--                 'ФАРС',
--                 'ФАНТАСТИКА',
--                 'ИСТОРИЧЕСКИЙ',
--                 'ПОЭТИЧЕСКИЙ',
--                 'ЭКСПЕРИМЕНТАЛЬНЫЙ',
--                 'ТЕАТРАЛЬНАЯ ПОЭЗИЯ',
--                 'ТРАГИКОМЕДИЯ',
--                 'МОНОДРАМА',
--                 'ПАНТОМИМА',
--                 'ЦЗАЦЗЮЙ',
--                 'ВОДЕВИЛЬ',
--                 'МИСТЕРИЯ',
--                 'ИЕРОДРАМА');
--         EXCEPTION
--             WHEN duplicate_object THEN
--                 RAISE NOTICE 'Type already exists, skipping creation.';
--         END;
--     END
-- $$;
--
--
-- alter type public.genre_type owner to postgres;
--
