version: '3.8'

services:
  postgres:
    container_name: theater_database_test
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sver25MD
      POSTGRES_DB: theater_information_system
    ports:
      - "5432:5432"
    restart: always
    networks:
      - network
networks:
  network:
    driver: bridge
